// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// ============================================================================
/// ACTION REQUIRED — fill in the 5 values below with your own Firebase
/// project's Android config before this will actually connect to Firebase.
///
/// This file was hand-written (not generated by the FlutterFire CLI) so that
/// you never need to install any local tooling — Firebase can be fully
/// initialized from pure Dart using just these 5 string values.
///
/// HOW TO GET THESE VALUES (no CLI, no downloads, ~3 minutes):
///   1. Go to https://console.firebase.google.com and create a project
///      (Google Analytics can be left OFF for simplicity).
///   2. In your new project, click the Android icon ("Add app").
///   3. Android package name — enter EXACTLY:
///        com.v2e.demo.sitevoice_v2e
///      (this must match the --org/--project-name used in the CI workflow,
///      see .github/workflows/build-apk.yml)
///   4. App nickname is optional. Click "Register app".
///   5. You do NOT need to download google-services.json — click
///      "Next" / "Continue to console" to skip past that step.
///   6. Go to Project settings (gear icon, top left) → General tab →
///      scroll to "Your apps" → click your Android app. You'll see a
///      config snippet containing apiKey, appId, messagingSenderId,
///      projectId, and storageBucket. Copy each value into the matching
///      field below.
///   7. Also enable the services you'll use:
///        Build → Firestore Database → Create database → Start in test mode
///        Build → Storage → Get started → Start in test mode
///      (Test mode rules are open/insecure by design and expire after 30
///      days — perfectly fine for a demo, but flag this before going live.)
///   8. Commit this file with your real values, push, and let the GitHub
///      Action rebuild the APK.
///
/// If you leave the placeholders as-is, the app will simply run in
/// local-only mode (Firebase init fails silently and is skipped) — your
/// demo will still work perfectly, it just won't sync to the cloud.
/// ============================================================================
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => android;

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.firebasestorage.app',
  );
}
